containers: containers.cpp
	g++ -g -o containers containers.cpp

fixa: containers.cpp
	g++ -o containers containers.cpp -DFIX_A

fixb: containers.cpp
	g++ -o containers containers.cpp -DFIX_B

clean:
	rm containers
